version: '3.11'
services:
  db:
    extends:
      file: docker-compose.db.yml
      service: db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:80"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
